### ISSUE TITLE
What does overridable mean?

### ISSUE THREAD

**Issue by bassjacob** [css-components/spec#2]
So I guess because of the Cascade and Selector parts of CSS, no matter what's chosen there's no real way to restrict someone including a stylesheet that styles a "pre-styled" component.

Are there more specific features desired when it comes to overriding styles?

**Comment by JedWatson** [comment]
Overridable means supporting (a) run-time changes to the stylesheet, e.g to support theme variables, and (b) supporting inline styles that override whatever's applied in the stylesheet.

To understand what I mean by (a), think of how you can change the way Bootstrap looks by changing values in its `variables.less` file. But imagine you can do this in JavaScript when the component is rendered.
