### ISSUE TITLE
"Buffering" and the necessary workarounds

### ISSUE THREAD

**Issue by taion** [css-components/spec#7]
One caveat with frameworks that inject CSS at runtime (v those that use inline styles or generate styles at compile time) is that they can leak implementation details if they make use of buffering.

Aphrodite notes this caveat here: https://github.com/Khan/aphrodite#style-injection-and-buffering

**Comment by threepointone** [comment]
fyi, they're also looking to move away from this model (good!) https://github.com/Khan/aphrodite/issues/115

**Comment by taion** [comment]
Looks like none of the modern frameworks have this issue any more, so closing for staleness.
